#!/bin/bash

# the plan to use (executable)
planner="rosrun ffha ffha"

# pddl inputs to the planner
domain="domain.pddl"
problem=$(python ../script.py ${1})

# Plan!
$planner -o $domain -f problems/$problem.pddl > solutions/plan_output_$problem.plan

echo "---------PLAN OUTPUT------------"

# show the plan to the user:
cat solutions/plan_output_$problem.plan

echo "--------------------------------"

# tell user that the planner output has been saved
echo "planner output saved as - plan_output_$problem.plan - in solutions folder"
